### ISSUE TITLE
Getting possible false negative on robot connection status in Grasshopper 

### ISSUE THREAD

**Issue by laurend** [createchaos/abb_communication#4]
robot says it is connected but grasshopper says that it isn't. 

<img width="817" alt="image" src="https://user-images.githubusercontent.com/1125979/104607392-c6f03180-564e-11eb-88e2-f455b5ff0f21.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/1125979/104608011-70cfbe00-564f-11eb-9e4d-ff6c4dc6c0cd.png">

**Comment by stefanaparascho** [comment]
solved
